name: React CI/CD

on:
  push:
    branches:
      - master

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t abbas737/react-kurs-isi:latest .

      - name: Push image
        run: docker push abbas737/react-kurs-isi:latest
          
          

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu"

      - name: Deploy EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu

            docker pull abbas737/react-kurs-isi:latest

            docker compose down

            docker compose up -d